### ISSUE TITLE
Not answering 9392?

### ISSUE THREAD

**Issue by bitwombat** [heichblatt/vagrant-openvas#3]
Seems something's not right after setup:

Setup complete, you can now access GSAD at:
  https://<IP>:9392

ifconfig tells me it's sitting at 10.0.2.15 but I can't get to it from my host at that addr, or localhost, or 127.0.0.1.  

Netstat makes it look like there's no routing to 10.x.  vagrant up shows the port 9392 forwarding, so I'd think https://localhost:9392 would work...

vagrant up shows complaints about shared folders and guest additions... do I need those for the webserver to be up?

openvasmd is running.

within the guest, nc localhost 9392 doesn't answer...

**Comment by bitwombat** [comment]
And a hint maybe:

> # openvas-check-setup 5.0
> openvas-check-setup 2.3.7
>   Test completeness and readiness of OpenVAS-8
>   (add '--v6' or '--v7' or '--v9'
>    if you want to check for another OpenVAS version)
> 
>   Please report us any non-detected problems and
>   help us to improve this check routine:
>   http://lists.wald.intevation.org/mailman/listinfo/openvas-discuss
> 
>   Send us the log-file (/tmp/openvas-check-setup.log) to help analyze the problem.
> 
>   Use the parameter --server to skip checks for client tools
>   like GSD and OpenVAS-CLI.
> 
> Step 1: Checking OpenVAS Scanner ... 
>         ERROR: OpenVAS Scanner too old or too new: 5.1.1
>         FIX: Please install OpenVAS Scanner 5.0.
>         HINT: Please see the --v6/7/8/9 command line options to check other major versions.
> 
>  ERROR: Your OpenVAS-8 installation is not yet complete!
>

**Comment by heichblatt** [comment]
Hello @bitwombat,

I have not used this repository for years and to be honest forgot about it. Since I don't use it anymore, I cannot commit any resources to it. If you want to, please take over.

Cheers and sorry. ;)
